// Portable workspace interactions. Example sources and entries are explicitly illustrative.
const workspacePrototype = (() => {
 const state={history:[],index:-1,replaying:false,canvasMode:'distilled',positions:new Map(),collapsed:new Set(),branches:[],sourceIds:new Set(),focus:null,exampleEntries:null,exploreOrigin:null,viewports:new Map(),camera:{x:0,y:0}};
 const el=selector=>document.querySelector(selector);
 const routeKey=route=>JSON.stringify([route.view,route.layer,route.anchor]);
 const readingSource=()=>ideaSources.find(source=>source.layer===readerLayer||readerLayer===`source:${source.id}`);
 function rememberPosition(){const current=state.history[state.index];if(!current)return;current.scroll=el('#stage')?.scrollTop||0;const viewport=el('#canvas-viewport');if(viewport)current.camera={...state.camera,zoom:canvasZoom};}
 function beforeNavigate(nextView,layer,anchor){
  state.focus=anchor;
  if(state.replaying)return;
  rememberPosition();
  const route={view:nextView,layer:nextView==='reader'?layer:'base',anchor,scroll:0};
  if(state.history[state.index]&&routeKey(state.history[state.index])===routeKey(route))return;
  state.history=state.history.slice(0,state.index+1);state.history.push(route);state.index++;
 }
 function afterNavigate(){
  updateMaterials();
  if(state.focus&&view==='reader')revealAnchor(state.focus);
  if(state.replaying){const route=state.history[state.index];el('#stage').scrollTop=route.scroll||0;const viewport=el('#canvas-viewport');if(viewport&&route.camera){state.camera={x:route.camera.x,y:route.camera.y};canvasZoom=route.camera.zoom;paintCamera();}}
 }
 function travel(direction){rememberPosition();const index=state.index+direction;if(index<0||index>=state.history.length)return;state.index=index;const route=state.history[index];state.replaying=true;setView(route.view,route.layer,route.anchor);state.replaying=false;el('#stage').focus({preventScroll:true});}
 function toolbar(){return `<div class="workspace-history"><button class="icon-button" data-workspace-action="back" aria-label="Go back" ${state.index<=0?'disabled':''}>${icon('back')}</button><button class="icon-button" data-workspace-action="forward" aria-label="Go forward" ${state.index>=state.history.length-1?'disabled':''}>${icon('arrow')}</button></div>`;}
 function globalActions(){return `<button class="quiet" data-workspace-action="explore">${icon('question')} Explore</button><button class="quiet" data-workspace-action="add-source">${icon('plus')} Add source</button>`;}
 function updateMaterials(){
  let section=el('#workspace-materials');if(!section){section=document.createElement('div');section.id='workspace-materials';el('#learning-outline').append(section);}
  section.innerHTML=(state.sourceIds.size?`<details class="topic-group" open><summary>${icon('back')}<span>Sources</span></summary><div class="topic-items">${[...state.sourceIds].map(id=>{const source=ideaSources.find(item=>item.id===id);return `<button data-workspace-action="read-source" data-source-id="${id}" ${readerLayer===`source:${id}`&&view==='reader'?'aria-current="page"':''}>${icon('book')}<span>${escapeHtml(source.title)}</span></button>`;}).join('')}</div></details>`:'')+(state.branches.length?`<details class="topic-group" open><summary>${icon('back')}<span>Explorations</span></summary><div class="topic-items">${state.branches.map(branch=>`<button data-workspace-action="open-branch" data-branch-id="${branch.id}" ${readerLayer===`branch:${branch.id}`&&view==='reader'?'aria-current="page"':''}>${icon('question')}<span>${escapeHtml(branch.question)}</span></button>`).join('')}</div></details>`:'');
 }
 function openSource(id,anchor=null){const source=ideaSources.find(item=>item.id===id);if(!source)return;if(!source.layer)state.sourceIds.add(id);readerPanelOpen=false;setView('reader',source.layer||`source:${id}`,anchor);if(!anchor)el('#stage').focus({preventScroll:true});}
 function openAnchor(anchor){if(el('#idea-dialog').open)el('#idea-dialog').close();openSource(anchor.sourceId,anchor);}
 function revealAnchor(anchor){
  const source=ideaSources.find(item=>item.id===anchor.sourceId);
  const paragraphs=[...document.querySelectorAll('.article p')];
  const paragraph=paragraphs.find(p=>p.dataset.passage===String(anchor.passage)&&p.dataset.sourceId===anchor.sourceId)||paragraphs.find(p=>p.textContent===source?.passages[anchor.passage]);
  if(!paragraph){announce('This source highlight is not available in the current text.');return;}
  let start=anchor.start;
  if(paragraph.textContent.slice(start,anchor.end)!==anchor.quote){start=paragraph.textContent.indexOf(anchor.quote);if(start<0||paragraph.textContent.indexOf(anchor.quote,start+1)>=0){announce('This highlight no longer matches this source version.');return;}}
  const end=start+anchor.quote.length;const walker=document.createTreeWalker(paragraph,NodeFilter.SHOW_TEXT);let offset=0,startNode,endNode,startOffset,endOffset;
  while(walker.nextNode()){const node=walker.currentNode;const next=offset+node.textContent.length;if(!startNode&&start<next){startNode=node;startOffset=start-offset;}if(end<=next){endNode=node;endOffset=end-offset;break;}offset=next;}
  if(!startNode||!endNode)return;
  const range=document.createRange();range.setStart(startNode,startOffset);range.setEnd(endNode,endOffset);const mark=document.createElement('mark');mark.className='reading-target';mark.tabIndex=-1;mark.append(range.extractContents());range.insertNode(mark);mark.scrollIntoView({block:'center',behavior:'instant'});mark.focus({preventScroll:true});announce('Opened the exact source highlight.');
 }
 function renderContextReader(){
  const branch=state.branches.find(item=>readerLayer===`branch:${item.id}`);
  if(branch)return header('Exploration')+`<div class="page exploration-page"><span class="small muted">Saved question · same project</span><h1>${escapeHtml(branch.question)}</h1><p class="serif">From ${escapeHtml(branch.origin.title)}</p><button class="outline" data-workspace-action="return-origin" data-branch-id="${branch.id}">${icon('back')} Return to where this started</button><section class="exploration-context"><h2>Keep following the question</h2><p>The question and its starting context are saved in this prototype. New learning responses are not connected here yet.</p><div class="actions"><button class="outline" data-workspace-action="add-source">${icon('plus')} Bring in a source</button><button class="quiet" data-workspace-action="explore">Explore another question ${icon('arrow')}</button><button class="quiet" data-view="canvas">See it on Canvas ${icon('canvas')}</button></div></section></div>`;
  const source=ideaSources.find(item=>readerLayer===`source:${item.id}`);if(!source)return '';
  return header('Source',`<button class="quiet" data-action="compose-note">${icon('note')} Note</button>`)+`<div class="reader-layout" data-panel-open="${readerPanelOpen}"><article class="article"><p class="reading-meta">${escapeHtml(source.origin)}</p><h1>${escapeHtml(source.title)}</h1>${source.passages.map((text,index)=>`<p data-source-id="${source.id}" data-passage="${index}">${escapeHtml(text)}</p>`).join('')}<div class="actions"><button class="outline" data-action="compose-note">${icon('note')} Take a note</button><button class="quiet" data-workspace-action="explore">Follow a question ${icon('arrow')}</button></div>${source.url?`<p class="small"><a href="${escapeHtml(source.url)}" target="_blank" rel="noopener">Open original source</a></p>`:''}</article>${renderReaderPanel()}</div>`;
 }
 function showDialog(content){el('#workspace-dialog-content').innerHTML=content;el('#workspace-dialog').showModal();}
 function originItem(source){return source?.originItemId||(source?.layer?learningItems.find(item=>item.layer===source.layer)?.id:null)||null;}
 function currentOrigin(entry=null){const source=entry?.anchor?sourceFor(entry.anchor):view==='reader'?readingSource():null;const branch=view==='reader'?state.branches.find(item=>readerLayer===`branch:${item.id}`):null;return {view,layer:readerLayer,entryId:entry?.id||null,itemId:entry?.origin?.itemId||branch?.origin.itemId||originItem(source)||(view==='reader'?learningItems.find(item=>item.layer===readerLayer)?.id:null)||null,sourceId:entry?.origin?.sourceId||source?.id||branch?.origin.sourceId||null,anchor:entry?.anchor||state.focus,title:entry?entry.text:source?.title||({canvas:'Canvas',practical:'Practical work',playbook:'Playbook'}[view]||'this workspace')};}
 function explore(entry=null){state.exploreOrigin=currentOrigin(entry);showDialog(`<h2 id="workspace-dialog-title">Follow a question</h2><p class="small muted">From ${escapeHtml(state.exploreOrigin.title)}</p><form id="workspace-explore-form"><label for="explore-question">What do you want to understand next?</label><textarea id="explore-question" rows="3" required placeholder="Why does…? What changes if…?"></textarea><p class="small muted">Keep the starting context and continue in this project.</p><button class="primary" type="submit">Explore ${icon('arrow')}</button></form>`);el('#explore-question').focus();}
 function addSource(){state.sourceOrigin=currentOrigin();showDialog(`<h2 id="workspace-dialog-title">Add a source to this project</h2><form id="workspace-source-form"><label for="source-title-input">Title</label><input id="source-title-input" required placeholder="Paper, article or working notes"><label for="source-text-input">Source text</label><textarea id="source-text-input" rows="6" required placeholder="Paste the text you want to read and annotate"></textarea><label for="source-url-input">Original link (optional)</label><input id="source-url-input" type="url" placeholder="https://…"><p class="small muted">Pasted text stays in this temporary prototype. File and URL extraction are not connected.</p><button class="primary" type="submit">Add and read ${icon('arrow')}</button></form><div class="source-example-actions"><span class="small muted">Or explore an illustrative source</span>${ideaSources.filter(source=>['import-example','openalex-example','semantic-example'].includes(source.id)).map(source=>`<button class="quiet" data-workspace-action="read-source" data-source-id="${source.id}">${escapeHtml(source.title)} ${icon('arrow')}</button>`).join('')}</div>`);el('#source-title-input').focus();}
 function examples(){if(!state.exampleEntries){const a={id:'example-note-model',kind:'note',example:true,text:'Equal wheel speeds move the robot straight; a difference between them creates a turn.',anchor:passageAnchor(ideaSources[0],0)};const b={id:'example-note-surface',kind:'note',example:true,text:'The same wheel commands can lead to different headings when the surface changes.',anchor:passageAnchor(ideaSources.find(source=>source.id==='import-example'),1)};state.exampleEntries=[a,b,{id:'example-insight-model',kind:'insight',example:true,text:'A motion model is a prediction to test against the surface, not a guarantee of the robot’s path.',supportIds:[a.id,b.id]}];}return state.exampleEntries;}
 const questionEntries=()=>state.branches.map(branch=>({...branch,kind:'question',text:branch.question}));
 const boardEntries=()=>humanEntries.length||state.branches.length?[...humanEntries,...questionEntries()]:examples();
 const findEntry=id=>boardEntries().find(entry=>entry.id===id);
 const boardNotes=entry=>(entry.supportIds||[]).map(findEntry).filter(Boolean);
 function notePreview(note){if(note.kind==='question')return `<div class="nested-note"><button data-workspace-action="open-branch" data-branch-id="${note.id}">${icon('question')}<span>${escapeHtml(note.text)}</span></button><span class="anchor-origin">Your question · ${escapeHtml(note.origin.title)}</span></div>`;return `<div class="nested-note"><button data-workspace-action="inspect-entry" data-entry-id="${note.id}">${icon('note')}<span>${escapeHtml(note.text)}</span></button><button class="nested-source" data-workspace-action="read-entry" data-entry-id="${note.id}">${icon('book')} ${escapeHtml(sourceFor(note.anchor).title)} ${icon('out')}</button></div>`;}
 function pathCards(){
  const cards=[];let y=60;
  learningTopics.forEach(topic=>{cards.push({id:`topic-${topic.id}`,kind:'topic',topic,x:40,y,width:230});topic.items.forEach((item,index)=>cards.push({id:`chapter-${item.id}`,kind:'chapter',item,x:350,y:y+index*150,width:280}));y+=topic.items.length*150+100;});
  const sourceIds=new Set([...state.sourceIds,...boardEntries().filter(entry=>entry.anchor).map(entry=>entry.anchor.sourceId)]);
  [...sourceIds].map(id=>ideaSources.find(source=>source.id===id)).filter(source=>source&&!source.layer).forEach((source,index)=>cards.push({id:`source-${source.id}`,kind:'source',source,x:350,y:y+index*180,width:280}));
  return cards;
 }
 function entryOriginId(entry){const source=entry.anchor?sourceFor(entry.anchor):ideaSources.find(item=>item.id===entry.origin?.sourceId);if(source)return source.layer?`chapter-${originItem(source)}`:`source-${source.id}`;return entry.origin?.itemId?`chapter-${entry.origin.itemId}`:entry.origin?.entryId||null;}
 function buildCards(){
  const entries=boardEntries(),insights=entries.filter(entry=>entry.kind==='insight'),used=new Set(insights.flatMap(entry=>entry.supportIds||[]));const cards=pathCards();
  if(state.canvasMode==='distilled'){
   insights.forEach((entry,index)=>cards.push({id:entry.id,entry,kind:'insight',x:820,y:80+index*620,nested:boardNotes(entry),width:400}));
   entries.filter(entry=>entry.kind!=='insight'&&!used.has(entry.id)).forEach((entry,index)=>cards.push({id:entry.id,entry,kind:entry.kind,x:1320,y:80+index*350,width:340}));
  }else{
   entries.filter(entry=>entry.kind==='note'||entry.kind==='question').forEach((entry,index)=>{if(entry.anchor)cards.push({id:`highlight-${entry.id}`,entry,kind:'highlight',x:740,y:80+index*370,width:320});cards.push({id:entry.id,entry,kind:entry.kind,x:1160,y:80+index*370,width:340});});
   insights.forEach((entry,index)=>cards.push({id:entry.id,entry,kind:'insight',x:1620,y:120+index*410,width:380}));
   entries.filter(entry=>entry.kind==='observation').forEach((entry,index)=>cards.push({id:entry.id,entry,kind:'observation',x:1160,y:100+(entries.length+index)*370,width:340}));
  }
  return cards;
 }
 function cardContent(card){
  if(card.topic)return `<span class="board-kind">Topic</span><button class="board-title" data-learning-item="${card.topic.items[0].id}">${escapeHtml(card.topic.title)}</button>`;
  if(card.item)return `<span class="board-kind">${card.item.tool?'Activity':'Chapter / concept'}${card.item.preview?' · preview':''}</span><button class="board-title" data-learning-item="${card.item.id}">${escapeHtml(card.item.title)}</button>`;
  if(card.source)return `<span class="board-kind">Source</span><button class="board-title" data-workspace-action="read-source" data-source-id="${card.source.id}">${escapeHtml(card.source.title)}</button>`;
  if(card.entry?.kind==='question')return `<span class="board-kind">Your question</span><button class="board-title" data-workspace-action="open-branch" data-branch-id="${card.entry.id}">${escapeHtml(card.entry.text)}</button><p class="small muted">From ${escapeHtml(card.entry.origin.title)}</p>`;

  if(card.branch)return `<span class="board-kind">Saved question</span><button class="board-title" data-workspace-action="open-branch" data-branch-id="${card.branch.id}">${escapeHtml(card.branch.question)}</button><p class="small muted">From ${escapeHtml(card.branch.origin.title)}</p>`;

  const entry=card.entry;
  if(card.kind==='highlight')return `<span class="board-kind">Source highlight</span><p class="board-text board-quote">${escapeHtml(entry.anchor.quote)}</p><button class="nested-source" data-workspace-action="read-entry" data-entry-id="${entry.id}">${icon('book')} ${escapeHtml(sourceFor(entry.anchor).title)} · ¶${entry.anchor.passage+1} ${icon('out')}</button>`;
  const label=entry.example?`Example ${entry.kind}`:entryLabel(entry);
  return `<span class="board-kind">${icon(entry.kind==='insight'?'insight':'note')} ${label}</span><button class="board-title" data-workspace-action="inspect-entry" data-entry-id="${entry.id}">${escapeHtml(entry.text)}</button>${card.nested?.length?`<button class="nested-toggle" data-workspace-action="toggle-nested" data-card-id="${card.id}" aria-expanded="${!state.collapsed.has(card.id)}">${icon('stack')} ${card.nested.length} linked notes / questions</button>${state.collapsed.has(card.id)?'':`<div class="nested-notes">${card.nested.map(notePreview).join('')}</div>`}`:entry.anchor?`<button class="nested-source" data-workspace-action="read-entry" data-entry-id="${entry.id}">${icon('book')} ${escapeHtml(sourceFor(entry.anchor).title)} ${icon('out')}</button>`:''}`;
 }
 function renderCanvas(){
  const cards=buildCards();
  return `<header class="canvas-topbar"><div class="workspace-heading">${toolbar()}<strong>Canvas</strong><span class="small muted canvas-project">Learning robotics</span></div><div class="segmented" role="group" aria-label="Map detail"><button data-workspace-action="distilled" aria-pressed="${state.canvasMode==='distilled'}">Distilled</button><button data-workspace-action="expanded" aria-pressed="${state.canvasMode==='expanded'}">Expanded</button></div><div class="actions"><button class="quiet" data-action="canvas-compose-insight" aria-label="Create insight" title="Create insight">${icon('plus')}<span>Create insight</span></button><button class="icon-button" data-workspace-action="explore" aria-label="Explore" title="Explore">${icon('question')}</button><button class="icon-button" data-workspace-action="add-source" aria-label="Add source" title="Add source">${icon('book')}</button><button class="icon-button" data-action="theme" aria-label="Switch to ${theme==='dark'?'light':'dark'} theme" title="Switch theme">${icon('sun')}</button></div></header><div class="canvas-viewport whiteboard-viewport" id="canvas-viewport" tabindex="0" role="region" aria-label="Infinite canvas. Drag background or use arrow keys to pan; control plus wheel to zoom."><div class="canvas-space" id="canvas-space"><div class="canvas-world whiteboard-world" id="canvas-world" style="transform:scale(${canvasZoom})"><svg class="canvas-connections" aria-hidden="true"></svg>${cards.map(card=>{const position=state.positions.get(`${state.canvasMode}:${card.id}`)||card;return `<article class="board-card board-${card.kind}" data-card="${card.id}" style="left:${position.x}px;top:${position.y}px;width:${card.width}px"><button class="board-drag" aria-label="Move ${escapeHtml(card.entry?.text||card.topic?.title||card.item?.title||card.source?.title||'card')}" title="Drag to move; arrow keys also work">${icon('stack')}</button>${cardContent(card)}</article>`;}).join('')}</div></div></div><div class="canvas-bottom"><button data-workspace-action="zoom-out" aria-label="Zoom out">−</button><span id="zoom-label">${Math.round(canvasZoom*100)}%</span><button data-workspace-action="zoom-in" aria-label="Zoom in">+</button><button data-workspace-action="fit">Fit map</button></div>${!humanEntries.length&&!state.branches.length?'<span class="canvas-example-label">Illustrative example map</span>':''}<aside id="canvas-detail" class="canvas-detail" hidden></aside>`;
 }
 function boardEdges(){
  const edges=learningTopics.flatMap(topic=>topic.items.map(item=>[`topic-${topic.id}`,`chapter-${item.id}`]));
  const cards=buildCards();cards.filter(card=>card.source?.originItemId).forEach(card=>edges.push([`chapter-${card.source.originItemId}`,card.id]));
  boardEntries().forEach(entry=>{
   if(entry.kind==='insight'){if(state.canvasMode==='expanded')(entry.supportIds||[]).forEach(id=>edges.push([id,entry.id]));else boardNotes(entry).forEach(note=>{const origin=entryOriginId(note);if(origin)edges.push([origin,entry.id]);});return;}
   const origin=entryOriginId(entry),visible=cards.some(card=>card.id===entry.id);if(origin&&visible)edges.push([origin,entry.id]);
   if(state.canvasMode==='expanded'&&entry.anchor)edges.push([`highlight-${entry.id}`,entry.id]);
  });
  return [...new Map(edges.map(edge=>[edge.join(':'),edge])).values()];
 }
 function avoidInitialOverlap(){const bottoms=new Map();el('#canvas-world').querySelectorAll('.board-card').forEach(card=>{const column=card.offsetLeft;if(!state.positions.has(`${state.canvasMode}:${card.dataset.card}`))card.style.top=Math.max(card.offsetTop,bottoms.get(column)||0)+'px';bottoms.set(column,Math.max(bottoms.get(column)||0,card.offsetTop+card.offsetHeight+48));});}
 function arrange(){const world=el('#canvas-world');if(!world)return;let width=1100,height=700;world.querySelectorAll('.board-card').forEach(card=>{width=Math.max(width,card.offsetLeft+card.offsetWidth+100);height=Math.max(height,card.offsetTop+card.offsetHeight+100);});world.style.width=width+'px';world.style.height=height+'px';const svg=world.querySelector('svg');svg.innerHTML=boardEdges().map(([from,to])=>{const a=world.querySelector(`[data-card="${from}"]`),b=world.querySelector(`[data-card="${to}"]`);if(!a||!b)return '';const x1=a.offsetLeft+a.offsetWidth,y1=a.offsetTop+a.offsetHeight/2,x2=b.offsetLeft,y2=b.offsetTop+b.offsetHeight/2,m=(x1+x2)/2;return `<path data-from="${from}" data-to="${to}" d="M${x1} ${y1}C${m} ${y1} ${m} ${y2} ${x2} ${y2}"/>`;}).join('');}
 function bindCanvas(){
  const viewport=el('#canvas-viewport'),world=el('#canvas-world');
  world.querySelectorAll('.board-drag').forEach(handle=>{const card=handle.closest('.board-card');const remember=()=>{state.positions.set(`${state.canvasMode}:${card.dataset.card}`,{x:card.offsetLeft,y:card.offsetTop});arrange();};handle.onpointerdown=event=>{if(event.button!==0)return;event.preventDefault();const start={x:event.clientX,y:event.clientY,left:card.offsetLeft,top:card.offsetTop};handle.setPointerCapture(event.pointerId);card.classList.add('is-dragging');handle.onpointermove=move=>{card.style.left=(start.left+(move.clientX-start.x)/canvasZoom)+'px';card.style.top=(start.top+(move.clientY-start.y)/canvasZoom)+'px';remember();};const finish=()=>{handle.onpointermove=null;handle.onpointerup=null;handle.onpointercancel=null;card.classList.remove('is-dragging');};handle.onpointerup=finish;handle.onpointercancel=finish;};handle.onkeydown=event=>{const delta={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[event.key];if(!delta)return;event.preventDefault();card.style.left=(card.offsetLeft+delta[0])+'px';card.style.top=(card.offsetTop+delta[1])+'px';remember();};});
  viewport.onpointerdown=event=>{if(event.button!==0||event.target.closest('.board-card,button'))return;event.preventDefault();viewport.focus({preventScroll:true});const start={...state.camera};const pointer={x:event.clientX,y:event.clientY};viewport.setPointerCapture(event.pointerId);viewport.classList.add('is-panning');viewport.onpointermove=move=>{state.camera={x:start.x+move.clientX-pointer.x,y:start.y+move.clientY-pointer.y};paintCamera();};const finish=()=>{viewport.onpointermove=null;viewport.onpointerup=null;viewport.onpointercancel=null;viewport.classList.remove('is-panning');};viewport.onpointerup=finish;viewport.onpointercancel=finish;};
  viewport.addEventListener('wheel',event=>{event.preventDefault();if(event.ctrlKey||event.metaKey){const rect=viewport.getBoundingClientRect();zoomAt(canvasZoom*Math.exp(-event.deltaY*.005),{x:event.clientX-rect.left,y:event.clientY-rect.top});}else{const unit=event.deltaMode===1?16:event.deltaMode===2?viewport.clientHeight:1;state.camera.x-=event.deltaX*unit;state.camera.y-=event.deltaY*unit;paintCamera();}},{passive:false});
  viewport.onkeydown=event=>{if(event.target!==viewport)return;const delta={ArrowLeft:[80,0],ArrowRight:[-80,0],ArrowUp:[0,80],ArrowDown:[0,-80]}[event.key];if(delta){event.preventDefault();state.camera.x+=delta[0];state.camera.y+=delta[1];paintCamera();}else if(event.key==='+'||event.key==='='){event.preventDefault();zoom(canvasZoom*1.1);}else if(event.key==='-'){event.preventDefault();zoom(canvasZoom/1.1);}else if(event.key==='Home'){event.preventDefault();fit();}};
  viewport.addEventListener('focusin',event=>{const card=event.target.closest('.board-card');if(!card)return;viewport.scrollLeft=0;viewport.scrollTop=0;const bounds=card.getBoundingClientRect(),frame=viewport.getBoundingClientRect();if(bounds.left<frame.left||bounds.right>frame.right||bounds.top<frame.top||bounds.bottom>frame.bottom){state.camera.x+=frame.left+24-bounds.left;state.camera.y+=frame.top+24-bounds.top;paintCamera();}});
  avoidInitialOverlap();arrange();paintCamera();document.fonts?.ready.then(()=>{if(el('#canvas-world')===world){avoidInitialOverlap();arrange();}});
 }
 function paintCamera(){const viewport=el('#canvas-viewport');if(!viewport)return;el('#canvas-world').style.transform=`translate(${state.camera.x}px,${state.camera.y}px) scale(${canvasZoom})`;viewport.style.backgroundPosition=`${state.camera.x}px ${state.camera.y}px`;let dotPitch=24*canvasZoom;while(dotPitch<14)dotPitch*=2;viewport.style.backgroundSize=`${dotPitch}px ${dotPitch}px`;el('#zoom-label').textContent=Math.round(canvasZoom*100)+'%';}
 function zoomAt(value,point){const old=canvasZoom;canvasZoom=Math.max(.2,Math.min(1.5,value));state.camera={x:point.x-(point.x-state.camera.x)*canvasZoom/old,y:point.y-(point.y-state.camera.y)*canvasZoom/old};paintCamera();}
 function zoom(value){const viewport=el('#canvas-viewport');zoomAt(value,{x:viewport.clientWidth/2,y:viewport.clientHeight/2});}
 function fit(){const viewport=el('#canvas-viewport'),cards=[...document.querySelectorAll('.board-card')];if(!cards.length||!viewport.clientWidth)return;const left=Math.min(...cards.map(card=>card.offsetLeft)),top=Math.min(...cards.map(card=>card.offsetTop)),right=Math.max(...cards.map(card=>card.offsetLeft+card.offsetWidth)),bottom=Math.max(...cards.map(card=>card.offsetTop+card.offsetHeight));canvasZoom=Math.max(.2,Math.min(1,(viewport.clientWidth-80)/(right-left),(viewport.clientHeight-100)/(bottom-top)));state.camera={x:(viewport.clientWidth-(right-left)*canvasZoom)/2-left*canvasZoom,y:40-top*canvasZoom};paintCamera();}
 function refreshBoard(){el('#stage').innerHTML=renderCanvas();bindCanvas();}
 function changeMode(mode){if(mode===state.canvasMode)return;state.viewports.set(state.canvasMode,{zoom:canvasZoom,...state.camera});state.canvasMode=mode;const saved=state.viewports.get(mode);if(saved){canvasZoom=saved.zoom;state.camera={x:saved.x,y:saved.y};}refreshBoard();if(!saved){canvasZoom=.7;state.camera={x:16,y:16};paintCamera();}el(`[data-workspace-action="${mode}"]`).focus({preventScroll:true});}
 function rerender(){rememberPosition();const route=state.history[state.index];state.replaying=true;setView(view,readerLayer,route?.anchor||null);state.replaying=false;}
 function inspectEntry(id){const entry=findEntry(id);if(!entry)return;const detail=el('#canvas-detail');detail.hidden=false;detail.innerHTML=`<div class="row"><span class="small muted">${entry.example?'Illustrative example':entryLabel(entry)}</span><button class="icon-button" data-workspace-action="close-detail" aria-label="Close details">${icon('close')}</button></div><p>${escapeHtml(entry.text)}</p>${entry.kind==='insight'?boardNotes(entry).map(notePreview).join(''):entry.anchor?`<blockquote>${escapeHtml(entry.anchor.quote)}</blockquote><button class="outline" data-workspace-action="read-entry" data-entry-id="${entry.id}">Open exact highlight ${icon('out')}</button>`:''}<button class="quiet" data-workspace-action="explore-entry" data-entry-id="${entry.id}">Explore from here ${icon('question')}</button>`;}
 const actions={'resume-reading':()=>setView('reader',readerLayer),back:()=>travel(-1),forward:()=>travel(1),explore:()=>explore(),'add-source':addSource,'read-source':button=>{if(el('#workspace-dialog').open)el('#workspace-dialog').close();if(el('#idea-dialog').open)el('#idea-dialog').close();openSource(button.dataset.sourceId);},'open-branch':button=>setView('reader',`branch:${button.dataset.branchId}`),'return-origin':button=>{const origin=state.branches.find(branch=>branch.id===button.dataset.branchId)?.origin;if(origin)setView(origin.view,origin.layer,origin.anchor);},distilled:()=>changeMode('distilled'),expanded:()=>changeMode('expanded'),'toggle-nested':button=>{const id=button.dataset.cardId;state.collapsed.has(id)?state.collapsed.delete(id):state.collapsed.add(id);refreshBoard();el(`[data-card="${id}"] .nested-toggle`).focus({preventScroll:true});},'inspect-entry':button=>inspectEntry(button.dataset.entryId),'read-entry':button=>{const entry=findEntry(button.dataset.entryId);if(entry?.anchor)openAnchor(entry.anchor);},'explore-entry':button=>explore(findEntry(button.dataset.entryId)),'close-detail':()=>{el('#canvas-detail').hidden=true;},'zoom-in':()=>zoom(canvasZoom+.1),'zoom-out':()=>zoom(canvasZoom-.1),fit};
 function handleAction(button){const action=actions[button.dataset.workspaceAction];if(!action)return false;action(button);return true;}
 function handleSubmit(event){
  if(event.target.id==='workspace-explore-form'){event.preventDefault();const question=el('#explore-question').value.trim();if(!question)return true;const branch={id:crypto.randomUUID(),question,origin:state.exploreOrigin};state.branches.push(branch);el('#workspace-dialog').close();setView('reader',`branch:${branch.id}`);return true;}
  if(event.target.id==='workspace-source-form'){event.preventDefault();const title=el('#source-title-input').value.trim(),text=el('#source-text-input').value.trim(),url=el('#source-url-input').value.trim();if(!title||!text)return true;if(url&&!/^https?:\/\//i.test(url)){el('#source-url-input').setCustomValidity('Use an http or https link.');el('#source-url-input').reportValidity();return true;}const source={id:crypto.randomUUID(),title,originItemId:state.sourceOrigin?.itemId||null,origin:'Pasted source · temporary local text',passages:text.split(/\n\s*\n/).filter(Boolean),url};ideaSources.push(source);el('#workspace-dialog').close();openSource(source.id);return true;}
  return false;
 }
 return {beforeNavigate,afterNavigate,toolbar,globalActions,updateMaterials,renderContextReader,renderCanvas,bindCanvas,handleAction,handleSubmit,openAnchor,zoom,fit,rerender,questionEntries};
})();
