import type {
  SourceLicense,
  SourceRelationship,
} from '../../contracts/sourcing.js';
import { freezeUniversityValue, type UniversityCandidate } from './types.js';

export const UNIVERSITY_DIRECTORY_IDS = {
  stanfordCs229: 'univ_stan_cs229',
  stanfordCs229Videos: 'univ_stan_cs229_vid',
  stanfordCs231n: 'univ_stan_cs231n',
  stanfordCs231nLecture1: 'univ_stan_cs231n_l1',
  berkeleyCs61a: 'univ_berk_cs61a',
  berkeleyCs61aFunctions: 'univ_berk_cs61a_fn',
  berkeleyComposingPrograms: 'univ_berk_compprog',
  harvardCs50x: 'univ_harv_cs50x',
  harvardCs50xLecture0: 'univ_harv_cs50x_l0',
  harvardCs50ai: 'univ_harv_cs50ai',
  harvardCs50aiSearch: 'univ_harv_cs50ai_sr',
  harvardCs50p: 'univ_harv_cs50p',
  harvardCs50pFunctions: 'univ_harv_cs50p_fn',
  mit6100l: 'univ_mit_6100l',
  yalePhys200: 'univ_yale_phys200',
  cmuOliPsych: 'univ_cmu_oli_psych',
} as const;

const UNKNOWN_LICENSE: SourceLicense = { status: 'unknown' };
const CC_BY_SA_3: SourceLicense = {
  status: 'known',
  name: 'Creative Commons Attribution-ShareAlike 3.0 Unported',
  spdxId: 'CC-BY-SA-3.0',
  url: 'https://creativecommons.org/licenses/by-sa/3.0/',
};
const CC_BY_NC_SA_4: SourceLicense = {
  status: 'known',
  name: 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International',
  spdxId: 'CC-BY-NC-SA-4.0',
  url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
};

function lectureOf(parentId: string): SourceRelationship {
  return {
    kind: 'lecture-of-course',
    parentSourceId: parentId,
    parentProviderIds: [{ provider: 'curated-catalog', id: parentId }],
  };
}

function directoryCourse(entry: UniversityCandidate): UniversityCandidate {
  return entry;
}

export const EXTERNAL_COURSE_DIRECTORY: readonly UniversityCandidate[] =
  freezeUniversityValue([
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.stanfordCs229,
      sourceId: UNIVERSITY_DIRECTORY_IDS.stanfordCs229,
      title: 'CS229 Machine Learning',
      kind: 'course',
      institution: 'Stanford University',
      courseCode: 'CS229',
      authors: ['Andrew Ng'],
      originalUrl: 'https://cs229.stanford.edu/syllabus-summer2020.html',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://see.stanford.edu/Course/CS229',
      format: 'external-reading',
      topicTags: [
        'linear-regression',
        'gradient-descent',
        'probability',
        'supervised-learning',
        'unsupervised-learning',
        'reinforcement-learning',
        'machine-learning',
      ],
      metadataSummary:
        'Learn linear regression, gradient descent, probability, and supervised, unsupervised, and reinforcement learning from Stanford CS229, using the public syllabus and official lecture videos.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.stanfordCs229Videos,
      sourceId: UNIVERSITY_DIRECTORY_IDS.stanfordCs229Videos,
      title: 'CS229 Machine Learning — official videos and transcripts',
      kind: 'lecture',
      institution: 'Stanford University',
      courseCode: 'CS229',
      authors: ['Andrew Ng'],
      originalUrl: 'https://see.stanford.edu/Course/CS229',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://see.stanford.edu/Course/CS229',
      format: 'external-reading',
      topicTags: [
        'machine-learning',
        'linear-regression',
        'gradient-descent',
        'probability',
      ],
      metadataSummary:
        'Watch Stanford Engineering Everywhere CS229 lectures and read the official HTML/PDF transcripts for the core machine-learning sequence.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.stanfordCs229)],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.stanfordCs231n,
      sourceId: UNIVERSITY_DIRECTORY_IDS.stanfordCs231n,
      title: 'CS231n Deep Learning for Computer Vision',
      kind: 'course',
      institution: 'Stanford University',
      courseCode: 'CS231n',
      authors: ['Stanford CS231n'],
      originalUrl: 'https://cs231n.stanford.edu/2025/index.html',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs231n.github.io/',
      format: 'external-reading',
      topicTags: [
        'neural-networks',
        'computer-vision',
        'backpropagation',
        'image-classification',
        'deep-learning',
      ],
      metadataSummary:
        'Learn neural networks, backpropagation, and image classification for computer vision from the public 2025 CS231n course, notes, and Stanford Online lectures.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.stanfordCs231nLecture1,
      sourceId: UNIVERSITY_DIRECTORY_IDS.stanfordCs231nLecture1,
      title: 'CS231n Lecture 1 — Deep Learning for Computer Vision',
      kind: 'lecture',
      institution: 'Stanford University',
      courseCode: 'CS231n',
      authors: ['Stanford CS231n'],
      originalUrl: 'https://www.youtube.com/watch?v=2fq9wYslV0A',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs231n.stanford.edu/2025/index.html',
      format: 'external-reading',
      topicTags: ['computer-vision', 'deep-learning', 'neural-networks'],
      metadataSummary:
        'Watch the official Stanford Online CS231n 2025 lecture 1 introduction to deep learning for computer vision. On-campus 2026 recordings are not this public edition.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.stanfordCs231n)],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.berkeleyCs61a,
      sourceId: UNIVERSITY_DIRECTORY_IDS.berkeleyCs61a,
      title: 'CS61A Structure and Interpretation of Computer Programs',
      kind: 'course',
      institution: 'University of California, Berkeley',
      courseCode: 'CS61A',
      authors: ['UC Berkeley CS61A'],
      originalUrl: 'https://cs61a.org/fa26/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs61a.org/fa26/',
      format: 'external-reading',
      topicTags: [
        'python',
        'functions',
        'abstraction',
        'recursion',
        'programming',
      ],
      metadataSummary:
        'Learn Python, functions, abstraction, and recursion in Berkeley CS61A, with official lecture videos and the Composing Programs textbook.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.berkeleyCs61aFunctions,
      sourceId: UNIVERSITY_DIRECTORY_IDS.berkeleyCs61aFunctions,
      title: 'CS61A — Functions',
      kind: 'lecture',
      institution: 'University of California, Berkeley',
      courseCode: 'CS61A',
      authors: ['UC Berkeley CS61A'],
      originalUrl:
        'https://www.youtube.com/watch?v=gNv81_4X0uU&list=PL6BsET-8jgYULSxiV2garZ0FxbnXR08MP&index=1',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs61a.org/fa26/',
      format: 'external-reading',
      topicTags: ['python', 'functions', 'abstraction'],
      metadataSummary:
        'Watch the official CS61A Functions lecture to see how Python functions express abstraction in the course sequence.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.berkeleyCs61a)],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.berkeleyComposingPrograms,
      sourceId: UNIVERSITY_DIRECTORY_IDS.berkeleyComposingPrograms,
      title: 'Composing Programs — Defining New Functions',
      kind: 'textbook',
      institution: 'University of California, Berkeley',
      courseCode: 'CS61A',
      authors: ['John DeNero'],
      originalUrl: 'https://composingprograms.com/3ed/defining-new-functions/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://composingprograms.com/',
      format: 'external-reading',
      topicTags: ['python', 'functions', 'abstraction'],
      metadataSummary:
        'Read how to define new functions in Python in Composing Programs, the CS61A textbook companion for abstraction and functional programming.',
      relationships: [],
      license: CC_BY_SA_3,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50x,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50x,
      title: 'CS50x Introduction to Computer Science',
      kind: 'course',
      institution: 'Harvard University',
      courseCode: 'CS50x',
      authors: ['David J. Malan'],
      originalUrl: 'https://cs50.harvard.edu/x/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/x/',
      format: 'external-reading',
      topicTags: ['introductory-cs', 'algorithms', 'c', 'python', 'sql', 'web'],
      metadataSummary:
        'Learn introductory computer science, algorithms, C, Python, SQL, and web programming through Harvard CS50x lectures, notes, and the official playlist.',
      relationships: [],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50xLecture0,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50xLecture0,
      title: 'CS50x Lecture 0 — Scratch',
      kind: 'lecture',
      institution: 'Harvard University',
      courseCode: 'CS50x',
      authors: ['David J. Malan'],
      originalUrl: 'https://www.youtube.com/watch?v=UuIEbpQms8o',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/x/notes/0/',
      format: 'external-reading',
      topicTags: ['introductory-cs', 'algorithms'],
      metadataSummary:
        'Watch CS50x Lecture 0 and open the official notes to start computational thinking, algorithms, and the course tools.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.harvardCs50x)],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50ai,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50ai,
      title: 'CS50 AI Introduction to Artificial Intelligence with Python',
      kind: 'course',
      institution: 'Harvard University',
      courseCode: 'CS50 AI',
      authors: ['David J. Malan'],
      originalUrl: 'https://cs50.harvard.edu/ai/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/ai/',
      format: 'external-reading',
      topicTags: [
        'search',
        'knowledge',
        'uncertainty',
        'machine-learning',
        'neural-networks',
        'nlp',
      ],
      metadataSummary:
        'Learn search, knowledge, uncertainty, machine learning, neural networks, and NLP in Harvard CS50 AI, with the official playlist and notes.',
      relationships: [],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50aiSearch,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50aiSearch,
      title: 'CS50 AI — Search',
      kind: 'lecture',
      institution: 'Harvard University',
      courseCode: 'CS50 AI',
      authors: ['David J. Malan'],
      originalUrl: 'https://www.youtube.com/watch?v=WbzNRTTrX0g',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/ai/notes/0/',
      format: 'external-reading',
      topicTags: ['search', 'artificial-intelligence', 'python'],
      metadataSummary:
        'Watch the CS50 AI Search lecture and read the official notes to learn how search algorithms explore problem spaces.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.harvardCs50ai)],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50p,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50p,
      title: 'CS50P Introduction to Programming with Python',
      kind: 'course',
      institution: 'Harvard University',
      courseCode: 'CS50P',
      authors: ['David J. Malan'],
      originalUrl: 'https://cs50.harvard.edu/python/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/python/',
      format: 'external-reading',
      topicTags: ['python', 'functions', 'testing', 'files', 'oop'],
      metadataSummary:
        'Learn beginner Python, functions, testing, files, and object-oriented programming in Harvard CS50P, with lectures, notes, and the official playlist.',
      relationships: [],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.harvardCs50pFunctions,
      sourceId: UNIVERSITY_DIRECTORY_IDS.harvardCs50pFunctions,
      title: 'CS50P — Functions',
      kind: 'lecture',
      institution: 'Harvard University',
      courseCode: 'CS50P',
      authors: ['David J. Malan'],
      originalUrl: 'https://www.youtube.com/watch?v=JP7ITIXGpHk',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://cs50.harvard.edu/python/notes/0/',
      format: 'external-reading',
      topicTags: ['python', 'functions'],
      metadataSummary:
        'Watch the CS50P Functions lecture and open the official notes to start writing and calling Python functions.',
      relationships: [lectureOf(UNIVERSITY_DIRECTORY_IDS.harvardCs50p)],
      license: CC_BY_NC_SA_4,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.mit6100l,
      sourceId: UNIVERSITY_DIRECTORY_IDS.mit6100l,
      title: 'Introduction to CS and Programming using Python',
      kind: 'course',
      institution: 'Massachusetts Institute of Technology',
      courseCode: '6.100L',
      authors: ['MIT OpenCourseWare'],
      originalUrl:
        'https://ocw.mit.edu/courses/6-100l-introduction-to-cs-and-programming-using-python-fall-2022/',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://ocw.mit.edu/pages/privacy-and-terms-of-use/',
      format: 'external-reading',
      topicTags: ['python', 'computer-science'],
      metadataSummary:
        'Browse MIT 6.100L to learn introductory programming in Python. Open the official OCW course page for lectures and materials.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.yalePhys200,
      sourceId: UNIVERSITY_DIRECTORY_IDS.yalePhys200,
      title: 'Fundamentals of Physics I',
      kind: 'course',
      institution: 'Yale University',
      courseCode: 'PHYS 200',
      authors: ['Open Yale Courses'],
      originalUrl: 'https://oyc.yale.edu/physics/phys-200',
      acquisitionUrl: null,
      licenseEvidenceUrl: 'https://oyc.yale.edu/terms',
      format: 'external-reading',
      topicTags: ['physics', 'mechanics'],
      metadataSummary:
        'Learn Newtonian mechanics and the foundations of physics from Yale PHYS 200 on Open Yale Courses.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
    directoryCourse({
      id: UNIVERSITY_DIRECTORY_IDS.cmuOliPsych,
      sourceId: UNIVERSITY_DIRECTORY_IDS.cmuOliPsych,
      title: 'Introduction to Psychology — Open & Free',
      kind: 'course',
      institution: 'Carnegie Mellon University',
      courseCode: 'OLI Introduction to Psychology',
      authors: ['Carnegie Mellon University OLI'],
      originalUrl:
        'https://oli.cmu.edu/courses/introduction-to-psychology-open-free/',
      acquisitionUrl: null,
      licenseEvidenceUrl:
        'https://oli.cmu.edu/about/policies/oli-terms-and-conditions/',
      format: 'external-reading',
      topicTags: ['psychology'],
      metadataSummary:
        'Study introductory psychology through Carnegie Mellon OLI’s open and free Introduction to Psychology course.',
      relationships: [],
      license: UNKNOWN_LICENSE,
      reachability: 'unchecked',
      permission: 'directory-only',
      extraction: 'none',
      indexing: 'not-indexed',
    }),
  ]);

export function externalCourseEntry(
  candidateId: string,
): UniversityCandidate | null {
  return (
    EXTERNAL_COURSE_DIRECTORY.find((entry) => entry.id === candidateId) ?? null
  );
}
